// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_dHVASIQ
NumericVector cpp_dHVASIQ(const NumericVector x, const NumericVector mu, const NumericVector sigma, const double quantile, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_dHVASIQ(SEXP xSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP quantileSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dHVASIQ(x, mu, sigma, quantile, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pHVASIQ
NumericVector cpp_pHVASIQ(const NumericVector q, const NumericVector mu, const NumericVector sigma, const double quantile, const bool lower_tail, const bool log_p);
RcppExport SEXP _vasicekreg_cpp_pHVASIQ(SEXP qSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP quantileSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pHVASIQ(q, mu, sigma, quantile, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qHVASIQ
NumericVector cpp_qHVASIQ(const NumericVector p, const NumericVector mu, const NumericVector sigma, const double quantile, const bool lower_tail, const bool log_p);
RcppExport SEXP _vasicekreg_cpp_qHVASIQ(SEXP pSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP quantileSEXP, SEXP lower_tailSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_tail(lower_tailSEXP);
    Rcpp::traits::input_parameter< const bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qHVASIQ(p, mu, sigma, quantile, lower_tail, log_p));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rHVASIQ
NumericVector cpp_rHVASIQ(const int n, const NumericVector mu, const NumericVector sigma, const double quantile);
RcppExport SEXP _vasicekreg_cpp_rHVASIQ(SEXP nSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP quantileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rHVASIQ(n, mu, sigma, quantile));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dlvasicek
NumericVector cpp_dlvasicek(const NumericVector x, const NumericVector alpha, const NumericVector theta, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_dlvasicek(SEXP xSEXP, SEXP alphaSEXP, SEXP thetaSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dlvasicek(x, alpha, theta, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_plvasicek
NumericVector cpp_plvasicek(const NumericVector x, const NumericVector alpha, const NumericVector theta, const bool lowertail, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_plvasicek(SEXP xSEXP, SEXP alphaSEXP, SEXP thetaSEXP, SEXP lowertailSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type lowertail(lowertailSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_plvasicek(x, alpha, theta, lowertail, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qlvasicek
NumericVector cpp_qlvasicek(const NumericVector p, const NumericVector alpha, const NumericVector theta, const bool lowertail, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_qlvasicek(SEXP pSEXP, SEXP alphaSEXP, SEXP thetaSEXP, SEXP lowertailSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type lowertail(lowertailSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qlvasicek(p, alpha, theta, lowertail, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rlvasicek
NumericVector cpp_rlvasicek(const int n, const NumericVector alpha, const NumericVector theta);
RcppExport SEXP _vasicekreg_cpp_rlvasicek(SEXP nSEXP, SEXP alphaSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rlvasicek(n, alpha, theta));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dLVASIQ
NumericVector cpp_dLVASIQ(const NumericVector x, const NumericVector mu, const NumericVector theta, const double quantile, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_dLVASIQ(SEXP xSEXP, SEXP muSEXP, SEXP thetaSEXP, SEXP quantileSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dLVASIQ(x, mu, theta, quantile, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pLVASIQ
NumericVector cpp_pLVASIQ(const NumericVector x, const NumericVector mu, const NumericVector theta, const double quantile, const bool lowertail, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_pLVASIQ(SEXP xSEXP, SEXP muSEXP, SEXP thetaSEXP, SEXP quantileSEXP, SEXP lowertailSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< const bool >::type lowertail(lowertailSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pLVASIQ(x, mu, theta, quantile, lowertail, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qLVASIQ
NumericVector cpp_qLVASIQ(const NumericVector p, const NumericVector mu, const NumericVector theta, const double quantile, const bool lowertail, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_qLVASIQ(SEXP pSEXP, SEXP muSEXP, SEXP thetaSEXP, SEXP quantileSEXP, SEXP lowertailSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< const bool >::type lowertail(lowertailSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qLVASIQ(p, mu, theta, quantile, lowertail, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_rLVASIQ
NumericVector cpp_rLVASIQ(const int n, const NumericVector mu, const NumericVector theta, const double quantile);
RcppExport SEXP _vasicekreg_cpp_rLVASIQ(SEXP nSEXP, SEXP muSEXP, SEXP thetaSEXP, SEXP quantileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_rLVASIQ(n, mu, theta, quantile));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mean_lvasicek
NumericVector cpp_mean_lvasicek(const NumericVector alpha, const NumericVector theta, const int npts);
RcppExport SEXP _vasicekreg_cpp_mean_lvasicek(SEXP alphaSEXP, SEXP thetaSEXP, SEXP nptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const int >::type npts(nptsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mean_lvasicek(alpha, theta, npts));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dNVASIM
NumericVector cpp_dNVASIM(const NumericVector x, const NumericVector alpha, const NumericVector theta, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_dNVASIM(SEXP xSEXP, SEXP alphaSEXP, SEXP thetaSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dNVASIM(x, alpha, theta, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pNVASIM
NumericVector cpp_pNVASIM(const NumericVector x, const NumericVector alpha, const NumericVector theta, const bool lowertail, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_pNVASIM(SEXP xSEXP, SEXP alphaSEXP, SEXP thetaSEXP, SEXP lowertailSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type lowertail(lowertailSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pNVASIM(x, alpha, theta, lowertail, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qNVASIM
NumericVector cpp_qNVASIM(const NumericVector x, const NumericVector alpha, const NumericVector theta, const bool lowertail, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_qNVASIM(SEXP xSEXP, SEXP alphaSEXP, SEXP thetaSEXP, SEXP lowertailSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type lowertail(lowertailSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qNVASIM(x, alpha, theta, lowertail, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dNVASIQ
NumericVector cpp_dNVASIQ(const NumericVector x, const NumericVector mu, const NumericVector theta, const double quantile, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_dNVASIQ(SEXP xSEXP, SEXP muSEXP, SEXP thetaSEXP, SEXP quantileSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dNVASIQ(x, mu, theta, quantile, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pNVASIQ
NumericVector cpp_pNVASIQ(const NumericVector x, const NumericVector mu, const NumericVector theta, const double quantile, const bool lowertail, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_pNVASIQ(SEXP xSEXP, SEXP muSEXP, SEXP thetaSEXP, SEXP quantileSEXP, SEXP lowertailSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< const bool >::type lowertail(lowertailSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pNVASIQ(x, mu, theta, quantile, lowertail, logprob));
    return rcpp_result_gen;
END_RCPP
}
// cpp_qNVASIQ
NumericVector cpp_qNVASIQ(const NumericVector x, const NumericVector mu, const NumericVector theta, const double quantile, const bool lowertail, const bool logprob);
RcppExport SEXP _vasicekreg_cpp_qNVASIQ(SEXP xSEXP, SEXP muSEXP, SEXP thetaSEXP, SEXP quantileSEXP, SEXP lowertailSEXP, SEXP logprobSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const double >::type quantile(quantileSEXP);
    Rcpp::traits::input_parameter< const bool >::type lowertail(lowertailSEXP);
    Rcpp::traits::input_parameter< const bool >::type logprob(logprobSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_qNVASIQ(x, mu, theta, quantile, lowertail, logprob));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vasicekreg_cpp_dHVASIQ", (DL_FUNC) &_vasicekreg_cpp_dHVASIQ, 5},
    {"_vasicekreg_cpp_pHVASIQ", (DL_FUNC) &_vasicekreg_cpp_pHVASIQ, 6},
    {"_vasicekreg_cpp_qHVASIQ", (DL_FUNC) &_vasicekreg_cpp_qHVASIQ, 6},
    {"_vasicekreg_cpp_rHVASIQ", (DL_FUNC) &_vasicekreg_cpp_rHVASIQ, 4},
    {"_vasicekreg_cpp_dlvasicek", (DL_FUNC) &_vasicekreg_cpp_dlvasicek, 4},
    {"_vasicekreg_cpp_plvasicek", (DL_FUNC) &_vasicekreg_cpp_plvasicek, 5},
    {"_vasicekreg_cpp_qlvasicek", (DL_FUNC) &_vasicekreg_cpp_qlvasicek, 5},
    {"_vasicekreg_cpp_rlvasicek", (DL_FUNC) &_vasicekreg_cpp_rlvasicek, 3},
    {"_vasicekreg_cpp_dLVASIQ", (DL_FUNC) &_vasicekreg_cpp_dLVASIQ, 5},
    {"_vasicekreg_cpp_pLVASIQ", (DL_FUNC) &_vasicekreg_cpp_pLVASIQ, 6},
    {"_vasicekreg_cpp_qLVASIQ", (DL_FUNC) &_vasicekreg_cpp_qLVASIQ, 6},
    {"_vasicekreg_cpp_rLVASIQ", (DL_FUNC) &_vasicekreg_cpp_rLVASIQ, 4},
    {"_vasicekreg_cpp_mean_lvasicek", (DL_FUNC) &_vasicekreg_cpp_mean_lvasicek, 3},
    {"_vasicekreg_cpp_dNVASIM", (DL_FUNC) &_vasicekreg_cpp_dNVASIM, 4},
    {"_vasicekreg_cpp_pNVASIM", (DL_FUNC) &_vasicekreg_cpp_pNVASIM, 5},
    {"_vasicekreg_cpp_qNVASIM", (DL_FUNC) &_vasicekreg_cpp_qNVASIM, 5},
    {"_vasicekreg_cpp_dNVASIQ", (DL_FUNC) &_vasicekreg_cpp_dNVASIQ, 5},
    {"_vasicekreg_cpp_pNVASIQ", (DL_FUNC) &_vasicekreg_cpp_pNVASIQ, 6},
    {"_vasicekreg_cpp_qNVASIQ", (DL_FUNC) &_vasicekreg_cpp_qNVASIQ, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_vasicekreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
