# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dHVASIQ <- function(x, mu, sigma, quantile = 0.5, logprob = FALSE) {
    .Call('_vasicekreg_cpp_dHVASIQ', PACKAGE = 'vasicekreg', x, mu, sigma, quantile, logprob)
}

cpp_pHVASIQ <- function(q, mu, sigma, quantile = 0.5, lower_tail = TRUE, log_p = FALSE) {
    .Call('_vasicekreg_cpp_pHVASIQ', PACKAGE = 'vasicekreg', q, mu, sigma, quantile, lower_tail, log_p)
}

cpp_qHVASIQ <- function(p, mu, sigma, quantile = 0.5, lower_tail = TRUE, log_p = FALSE) {
    .Call('_vasicekreg_cpp_qHVASIQ', PACKAGE = 'vasicekreg', p, mu, sigma, quantile, lower_tail, log_p)
}

cpp_rHVASIQ <- function(n, mu, sigma, quantile = 0.5) {
    .Call('_vasicekreg_cpp_rHVASIQ', PACKAGE = 'vasicekreg', n, mu, sigma, quantile)
}

cpp_dlvasicek <- function(x, alpha, theta, logprob = FALSE) {
    .Call('_vasicekreg_cpp_dlvasicek', PACKAGE = 'vasicekreg', x, alpha, theta, logprob)
}

cpp_plvasicek <- function(x, alpha, theta, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_plvasicek', PACKAGE = 'vasicekreg', x, alpha, theta, lowertail, logprob)
}

cpp_qlvasicek <- function(p, alpha, theta, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_qlvasicek', PACKAGE = 'vasicekreg', p, alpha, theta, lowertail, logprob)
}

cpp_rlvasicek <- function(n, alpha, theta) {
    .Call('_vasicekreg_cpp_rlvasicek', PACKAGE = 'vasicekreg', n, alpha, theta)
}

cpp_dLVASIQ <- function(x, mu, theta, quantile = 0.5, logprob = FALSE) {
    .Call('_vasicekreg_cpp_dLVASIQ', PACKAGE = 'vasicekreg', x, mu, theta, quantile, logprob)
}

cpp_pLVASIQ <- function(x, mu, theta, quantile = 0.5, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_pLVASIQ', PACKAGE = 'vasicekreg', x, mu, theta, quantile, lowertail, logprob)
}

cpp_qLVASIQ <- function(p, mu, theta, quantile = 0.5, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_qLVASIQ', PACKAGE = 'vasicekreg', p, mu, theta, quantile, lowertail, logprob)
}

cpp_rLVASIQ <- function(n, mu, theta, quantile = 0.5) {
    .Call('_vasicekreg_cpp_rLVASIQ', PACKAGE = 'vasicekreg', n, mu, theta, quantile)
}

cpp_mean_lvasicek <- function(alpha, theta, npts = 128L) {
    .Call('_vasicekreg_cpp_mean_lvasicek', PACKAGE = 'vasicekreg', alpha, theta, npts)
}

cpp_dNVASIM <- function(x, alpha, theta, logprob = FALSE) {
    .Call('_vasicekreg_cpp_dNVASIM', PACKAGE = 'vasicekreg', x, alpha, theta, logprob)
}

cpp_pNVASIM <- function(x, alpha, theta, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_pNVASIM', PACKAGE = 'vasicekreg', x, alpha, theta, lowertail, logprob)
}

cpp_qNVASIM <- function(x, alpha, theta, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_qNVASIM', PACKAGE = 'vasicekreg', x, alpha, theta, lowertail, logprob)
}

cpp_dNVASIQ <- function(x, mu, theta, quantile, logprob = FALSE) {
    .Call('_vasicekreg_cpp_dNVASIQ', PACKAGE = 'vasicekreg', x, mu, theta, quantile, logprob)
}

cpp_pNVASIQ <- function(x, mu, theta, quantile, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_pNVASIQ', PACKAGE = 'vasicekreg', x, mu, theta, quantile, lowertail, logprob)
}

cpp_qNVASIQ <- function(x, mu, theta, quantile, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_qNVASIQ', PACKAGE = 'vasicekreg', x, mu, theta, quantile, lowertail, logprob)
}

