# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dvasicekmean <- function(x, alpha, theta, logprob = FALSE) {
    .Call('_vasicekreg_cpp_dvasicekmean', PACKAGE = 'vasicekreg', x, alpha, theta, logprob)
}

cpp_pvasicekmean <- function(x, alpha, theta, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_pvasicekmean', PACKAGE = 'vasicekreg', x, alpha, theta, lowertail, logprob)
}

cpp_qvasicekmean <- function(x, alpha, theta, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_qvasicekmean', PACKAGE = 'vasicekreg', x, alpha, theta, lowertail, logprob)
}

cpp_dvasicekquant <- function(x, mu, theta, tau, logprob = FALSE) {
    .Call('_vasicekreg_cpp_dvasicekquant', PACKAGE = 'vasicekreg', x, mu, theta, tau, logprob)
}

cpp_pvasicekquant <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_pvasicekquant', PACKAGE = 'vasicekreg', x, mu, theta, tau, lowertail, logprob)
}

cpp_qvasicekquant <- function(x, mu, theta, tau, lowertail = TRUE, logprob = FALSE) {
    .Call('_vasicekreg_cpp_qvasicekquant', PACKAGE = 'vasicekreg', x, mu, theta, tau, lowertail, logprob)
}

